### PR TITLE
UCA-95: Code linting!

### PR DESCRIPTION
**Pull request by techninja**
# [UCA-95: Linting](https://fourkitchens.atlassian.net/browse/UCA-95)

### This PR does the following:
- Adds code linting configuration for JS and PHP

### Notes:
- Base D8 ESlint config seems to be configured to be ES6+ heavy, and is giving some inappropriate suggestions for clientside web-in-the-wild code. Need to tweak this before merging.
- This doesn't do anything for CI builds at the moment.

### Pull Request Deployment:
- Run `yarn` and `composer install` to get the new updates, then rebuild as usual

### Functional Testing:
- [x] Run `yarn lint php` to run php testing on custom module & theme code. Add a file doc or other non-fatal linting issue to any php or install file to see issues.
- [x] Run `yarn lint php fix` to have `phpcbf` attempt to fix the issues it sees.
- [x] Run `yarn lint js` and see errors on JS files (at least till we fix them or change the linting standards)
- [x] Run `yarn lint js fix` to have `eslint` attempt to fix the issues it sees.
- [x] Run `yarn lint` to see that both linting operations are run concurrently
- [x] Read the readme and see that it properly explains how to do this

### CODE REVIEW

**Comment by evanmwillhite** [comment]
Added theme to extensions so that it will evaluate the theme's `stellar.theme` file. Also, I noticed that it caught a php error (missing colon), but not a comment missing a period at the end. This is minor, but I have noticed it's pretty standard in our setups. Do we need that?

**Comment by evanmwillhite** [comment]
Running `yarn lint js` failed with `Cannot find module 'eslint-config-airbnb`

**Comment by techninja** [comment]
@evanmwillhite Was missing a package dep that was added, but then missed. And Also had to add theme files to the PHPCS script execution. The PHP lint config we're using comes directly from the Drupal coder standards. I suspect if we need to adjust this at all we'll need to make an extension/override. Try again and see if these adjustments help 😄

**Comment by evanmwillhite** [comment]
OK, it appears all of this is fixed. If you're OK with the linting fixes I made (some automated, some manual) to take care of errors AND we don't need to make our setup run linting before committing, then I think this is good to ship. Probably should get an eye from @americkson first.

**Pull request merged**
