### PR TITLE
UCA-69: Training node form

### PR DESCRIPTION
**Pull request by techninja**
# [UCA-69: Training coordinator form](https://fourkitchens.atlassian.net/browse/UCA-69)

**Based on #23, so merge that first** 

### This PR does the following:
- Adjusts permissions so training coordinator role can create/edit trainings
- Adds a new form widget to render the survey question integer list entry as a single checkbox
- Adds the form mode manager module and configures a survey form mode "Training" to allow configuration of a different form mode for surveys specific to training entity form embeds

### Functional Testing:
- [x] Login as admin, create a Training Program Coordinator user via /admin/people/create. 
- [x] Login as that user and go to /node/add
- [x] See that you're redirected to the training add node page
- [x] See that you can add both competency and task surveys, and that instead of a 1-5 rating, you enter in a value simply as a checkbox. Fill out the title and check a number of these and click save.
- [x] See that the node saves, then click edit and see that your saved values for task and competency display as entered

### CODE REVIEW

**Comment by evanmwillhite** [comment]
Ok, I've done some tweaking to labels and have added most of the fields in the document referenced except a couple:

1. keywords (not sure what this is)
2. Method of Delivery (this is a select or other kind of thing. Not sure how we're handling it on this project)

**Comment by americkson** [comment]
Getting this error when I try to create a Trading Coordinator account. It is for the Institutional Affiliation/Title field that is on the 'Clinical Research Professional' profile.

screen shot 2018-06-26 at 11 09 55 pm

This is happening when I attempt to create the account as an admin or as a registering user.

**Comment by americkson** [comment]
We should only be able to select institutions for the Institution/Organization Offering Training field, remove the job titles(sub items) like we did on the training coordinator registration form.

screen shot 2018-06-26 at 11 16 07 pm

**Comment by americkson** [comment]
Few more items:

- I think we should try add some field grouping to this form so that it is a bit more user friendly. If you want some guidance there let me know. 
- Let's rebuild the 'Brief Description of Training' field to just be a long text field WITHOUT a summary. And let's see about removing the 'about text formats'. Let's not use the 'Body' field.
- The cost field should be just a single field, not a multi field.
- I like the idea of making the 'Prerequisites for Training' field a multi text list but I wonder if we should consider making the 'add
- Let make the 'Additional information' field a text area as well.
- As a training coordinator, I should not be able to save or use revisions.


Love the selections for the tasks & competencies! Solid idea.

**Comment by evanmwillhite** [comment]
Gonna take a stab at what I can on this one and then if I hit any walls, I'll pass it to @techninja or @americkson

**Comment by evanmwillhite** [comment]
- [x] Getting this error when I try to create a Trading Coordinator account. It is for the Institutional Affiliation/Title field that is on the 'Clinical Research Professional' profile.
**I changed this to use the same entity reference view created by @techninja but using a new view display that shows all the terms. Not sure how this will conflict with shs, but it at least avoids the error.**
- [x] We should only be able to select institutions for the Institution/Organization Offering Training field, remove the job titles(sub items) like we did on the training coordinator registration form.
**I think I did this right, @techninja check me here.**
- [x] I think we should try add some field grouping to this form so that it is a bit more user friendly. If you want some guidance there let me know.
**I've done this, but wasn't sure what the logic should be behind the grouping.**
- [x] Let's rebuild the 'Brief Description of Training' field to just be a long text field WITHOUT a summary.
- [x] let's see about removing the 'about text formats'. Let's not use the 'Body' field.
- [x] The cost field should be just a single field, not a multi field.
- [ ] I like the idea of making the 'Prerequisites for Training' field a multi text list but I wonder if we should consider making the 'add
**I've done some styling to improve this section, but wasn't sure what you meant above. Looks like you might have gotten cut off.**
- [x] Let make the 'Additional information' field a text area as well.
- [x] As a training coordinator, I should not be able to save or use revisions.

**Comment by evanmwillhite** [comment]
Ready for review again, but see my comment above in case you have questions.

**Comment by americkson** [comment]
@evanmwillhite haha... opps! Here is what I meant with that cut off thought:
I like the idea of making the 'Prerequisites for Training' field a multi text list but I wonder if we should consider some theme adjustment for the 'add another item' buttons and adding help text.

If you can think of a quick idea to handle that type of field for the user I think it would be beneficial. It helps a little bit to have the field grouping now.

**Comment by americkson** [comment]
This one is looking pretty good, just needs some help on the front end.

screen shot 2018-06-27 at 10 00 42 pm

**Pull request merged**
