### PR TITLE
UCA-132: User administration and content block administrative views

### PR DESCRIPTION
**Pull request by evanmwillhite**
# [UCA-132: Create Admin view for content blocks](https://fourkitchens.atlassian.net/browse/UCA-132)

### Purpose:
- Give UGA admins ability to edit users (access to admin menu, user admin) and content blocks (new view containing bulk edit operations).

### Pull Request Deployment:
- `yarn rebuild`

### Functional Testing:
- [x] Log in and [create a new user](https://stellar.lndo.site/admin/people/create) with UGA Admin role
- [x] Login with that new user account and ensure you can access both the users page (and add/edit users) and the new Content > Content Blocks page and edit content blocks appropriately

### CODE REVIEW

**Comment by americkson** [comment]
@evanmwillhite  - Couple small things there, sorry I didn't include them in the details.

- Remove the ability to delete the content blocks (that way they don't accidentally remove them when config might be looking for them.
- add the ability to create new blocks (add a 'Add New Content Block' in the header of the view)

**Comment by evanmwillhite** [comment]
@americkson take a peek now and see if this solves those last 2 things.

**Comment by evanmwillhite** [comment]
Need to remove vbo

**Comment by evanmwillhite** [comment]
Ok, this is ready for review for real. :)

**Comment by americkson** [comment]
@evanmwillhite When you remove a module you need to uninstall it first. So you will want to do something like this:

- Uninstall the module via admin GUI or run: `lando drush pmu views_bulk_operations`
- run configuration export: `lando drush cex`
- commit changes 
- Remove the dependency: `composer remove drupal/views_bulk_operations`
- commit changes

👍

**Pull request merged**
